import os
from pathlib import Path

import numpy as np
from numpy.lib.format import open_memmap


in_dir = Path("/root/tmp/dji/eval_npzs/")
out_npz = in_dir / "gen_all.npz"
tmp_npy = in_dir / "gen_all.tmp.npy"

files = sorted(in_dir.glob("gen_0000000_0*.npz"))

# Avoid accidentally including previous merged file
files = [p for p in files if not p.name.endswith("_all.npz")]

print("Input files:")
for p in files:
    print(" ", p)

# Detect key/shape/dtype
meta = []
key = None
total = 0

for p in files:
    with np.load(p) as z:
        if key is None:
            # Usually "arr_0" or "images"
            key = "arr_0" if "arr_0" in z.files else z.files[0]
            print("Using key:", key)

        arr = z[key]
        print(p.name, arr.shape, arr.dtype)

        meta.append((p, arr.shape, arr.dtype))
        total += arr.shape[0]

first_shape = meta[0][1]
dtype = meta[0][2]
tail_shape = first_shape[1:]

for p, shape, dt in meta:
    assert dt == dtype, f"dtype mismatch: {p} has {dt}, expected {dtype}"
    assert shape[1:] == tail_shape, f"shape mismatch: {p} has {shape}, expected (*, {tail_shape})"

out_shape = (total, *tail_shape)
print("Output shape:", out_shape, dtype)

# Create temporary .npy memmap so we never hold all images in RAM
dst = open_memmap(tmp_npy, mode="w+", dtype=dtype, shape=out_shape)

offset = 0
for p, shape, _ in meta:
    n = shape[0]
    print(f"Copying {p.name}: [{offset}:{offset+n}]")

    with np.load(p) as z:
        arr = z[key]

        # Copy in mini-batches to reduce peak RAM during assignment
        bs = 512
        for s in range(0, n, bs):
            e = min(s + bs, n)
            dst[offset + s : offset + e] = arr[s:e]

    offset += n

dst.flush()
del dst

print("Writing final npz:", out_npz)

# Most FID evaluators expect arr_0 if generated by np.savez.
arr = np.load(tmp_npy, mmap_mode="r")
np.savez(out_npz, arr)

print("Done:", out_npz)
print("Removing temp:", tmp_npy)
os.remove(tmp_npy)
