stage_1:
  target: stage1.FineViTRAE
  params:
    encoder_name: dinov2-vit-b
    resolution: 256
    decoder_config_path: configs/decoder/ViTXL
    pretrained_decoder_path: checkpoints/dinov2b-k1/stage1/imagenet/dinov2b-k1/decoder.pt
    noise_tau: 0.0
    normalization_stat_path: null
    finevit_model_name: toilaluan/aabb
    finevit_normalization_stat_path: pretrained_models/stage1/imagenet/finevit-dinov2b-k1/stats.pt
    finevit_target_seq_length: 256
stage_2:
  target: stage2.models.DDT.DiTwDDTHeadIG
  params:
    latent_layout: "1d"
    input_size: 64
    patch_size:
    - 1
    - 1
    in_channels: 768
    hidden_size:
    - 1440
    - 2048
    depth:
    - 28
    - 2
    num_heads:
    - 20
    - 16
    mlp_ratio: 4.0
    base_model_depth: 8
  ckpt: null
conditioning:
  type: label
  cfg_dropout_prob: 0.1
  arch:
    num_t_tokens: 4
    num_c_tokens: 8
transport:
  prediction: x
  time_dist_type: logit-normal_0_1
sampler:
  num_steps: 100
guidance:
  cfg:
    scale: 1.0
    t_min: 0.0
    t_max: 1.0
  ig:
    scale: 1.78
    t_min: 0.10
    t_max: 1.0
dataset:
  target: imagenet
  type: hf
  data_dir: ./data/imagenet-256
  split: train
  condition_type: label
  shared_tmpdir: ~/tmp
training:
  epochs: 80
  global_batch_size: 2048
  grad_accum_steps: 1
  ema_decay: 0.9995
  num_workers: 4
  log_interval: 100
  checkpoint_interval: 1
  sample_every: 5000
  clip_grad: 1.0
  global_seed: 42
  optimizer:
    type: gmuon
    lr: 0.0002
    momentum: 0.95
    nesterov: true
    ns_coefficients_preset: POLAR_EXPRESS_COEFFICIENTS
    ns_use_kernels: false
    weight_decay: 0.0
  scheduler:
    type: linear
    warmup_epochs: 25
    decay_end_epoch: 50
    base_lr: 0.0002
    final_lr: 2.0e-05
    warmup_from_zero: false
  image_size: 256
eval:
  eval_interval: 5000
  eval_model: false
  eval_dir: results/stage2/eval
  datasets:
    imagenet:
      type: hf
      data_dir: ./data/imagenet-256
      split: val
      condition_type: label
      num_samples: 50000
      metrics:
      - fid
      - fdr6
      - mind6
misc:
  latent_size:
  - 64
  - 768
  num_classes: 1000
  time_dist_shift_dim: 49152
  time_dist_shift_base: 4096
